version: 2.1
orbs:
  gor: hubci/goreleaser@1.0.0
  go: circleci/go@1.7.0

workflows:
  main:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: 0.147.1
          go-version: 1.16.5
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
jobs:
  test:
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved  
    executor:
      name: go/default
      tag: '1.16.5'
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory      
#      - go/load-cache
      - go/mod-download
#      - go/save-cache      
      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES
      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

